spring:
  profiles:
    active: dev

# MyBatis配置
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.platform
  typeEnumsPackage: com.platform
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true
    #日志打印
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: true
  global-config:
    banner: false
    dbConfig:
      #逻辑删除
      logicDeleteValue: "null" # 逻辑已删除值(默认为 1)
      logicNotDeleteValue: 0 # 逻辑未删除值(默认为 0)

# MyBatis配置
mybatis-mate:
  cert:
    grant: kaola
    license: PsHdn6aZUaGodukzTgwLSE9NZUA5hCmZDsQHp4a9YpZc8BPNAeeRe5/tBeKOuSdyQQwwKukKf5ARMNpCTO/OaxvcvkwxKC0oH4HcG1hE2pXeZ6o2bVRti6VDg+xfcYzByd82T6yUP0XRxq2nDF8YGxNSNqZa0FFyS9eqWw30JTtJtrJW5XOas9R4Qls9LCKZ3/GKf7GMO/zsoUMpDQsjMP7lNIXOvxRwqwVinQtWF6TIcK59vPizkPbaguWDDQDC0YQaJGDlDVaepcSu6SfRySVCOnh/HwCdB5IAxlgJhQlcHTpLyFh1l2KkOc7ZmwJpvLtKKvoTrFWnJwbMlMAQAg==

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  # 合理化分页
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# xss设置
xss:
  # xss开关，Y/N，默认开
  enabled: Y
  # xss过滤
  excludes:
    - /chat/robot/*