# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 16364
    # 是否分配的直接内存
    direct-buffers: true

# 项目相关配置
platform:
  # 富文本路径 示例（ Windows配置D:/platform/uploadPath，Linux配置 /home/platform/uploadPath）
  rootPath: /data/uploadPath
  # 系统版本
  version: 1.0.0
  # 日志地址
  logPath: ./logs
  # 定时任务Y/N
  task: N
  # token超时时间（小时）
  timeout: 168
  # 消息秘钥
  secret: 3c17c816846c231c
  # 管理员账号
  username: super
  # 管理员密码
  password: admin

# 支付相关配置
pay:
  # 支付宝配置
  ali:
    # 应用编号
    appId: appId
    # 应用私钥
    appPrivateKey: appPrivateKey
    # 应用公钥
    appPublicPath: cert/test/appCertPublicKey.crt
    # 支付宝公钥
    aliPayPublicPath: cert/test/alipayCertPublicKey_RSA2.crt
    # 支付宝根证书
    aliPayRootPath: cert/test/alipayRootCert.crt
    # 支付网关
    serviceUrl: https://openapi.alipay.com/gateway.do

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 100MB

  # ShardingSphere 配置项
  shardingsphere:
    # 数据源配置
    datasource:
      # 所有数据源的名字
      names: master
      # 主库的数据源配置
      master:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/alpaca-im?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: root
        hikari:
          maximum-pool-size: 60
    # 拓展属性配置
    props:
      sql:
        # 打印 SQL
        show: false
    sharding:
      default-data-source-name: master

  # redis 配置
  redis:
    # 开关
    enabled: Y
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库
    database: 0
    # 密码
    password: ir2iV5G1d17N8okh
    # 超时
    timeout: 5000
    # 连接池
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 128
        # 连接池的最大数据库连接数
        max-active: 128
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
  # redis 配置
  other:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库
    database: 0
    # 密码
    password: ir2iV5G1d17N8okh

# MQ配置
rocketmq:
  # mq开关
  enabled: Y
  # 服务接入地址
  name-server: MQ_INST_rocketmxxxxxxxxxxxxxxxa_im.tdmq-rocketmq.ap-bj.public.tencenttdmq.com:9876
  # 生产者公共配置
  producer:
    # AccessKey
    access-key: AccessKey
    # SecretKey
    secret-key: SecretKey
    # 生产者组
    group: alpaca_im
  # 生产主题
  topic: alpaca_im

# 推送配置
push:
  # 个推开关
  enabled: Y
  # 个推appId
  appId: appId
  # 个推appKey
  appKey: appKey
  # 个推appSecret
  appSecret: appSecret
  # 个推masterSecret
  masterSecret: masterSecret
  
# 上传配置
upload:
  uploadType: kodo
  serverUrl: http://172.17.0.1
  accessKey: accessKey
  secretKey: secretKey
  bucket: bucket
  prefix: alpaca
  region: http://up-z2.qiniu.com
  
# 腾讯语音识别
tencent:
  enabled: Y
  appId: appId
  accessKey: accessKey
  secretKey: secretKey

# 日志配置
logging:
  level:
    com.platform: info
    org.springframework: warn
    org.springframework.scheduling: INFO
    org.apache.rocketmq: error